// <auto-generated />
using System;
using InterviewTraining.Infrastructure.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InterviewTraining.Infrastructure.Migrations
{
    [DbContext(typeof(InterviewContext))]
    [Migration("20260411150257_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InterviewTraining.Domain.AdditionalUserInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Уникальный идентификатор");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_utc")
                        .HasComment("Дата и время создания записи в таблице");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description")
                        .HasComment("Полное описание");

                    b.Property<string>("FullName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("full_name")
                        .HasComment("Полное имя пользователя");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("identity_user_id")
                        .HasComment("Идентификатор пользователя в Identity");

                    b.Property<bool>("InterviewScheduleAtAnyTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("interview_schedule_at_any_time")
                        .HasComment("Готов проводить интервью в любое время");

                    b.Property<bool>("IsCandidate")
                        .HasColumnType("boolean")
                        .HasColumnName("is_candidate")
                        .HasComment("Признак кандидата");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasComment("Признак удалена запись или нет");

                    b.Property<bool>("IsExpert")
                        .HasColumnType("boolean")
                        .HasColumnName("is_expert")
                        .HasComment("Признак эксперта");

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modified_utc")
                        .HasComment("Дата и время последнего изменения записи в таблице");

                    b.Property<string>("Photo")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("photo")
                        .HasComment("URL фото пользователя");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("short_description")
                        .HasComment("Краткое описание");

                    b.HasKey("Id");

                    b.HasIndex("IdentityUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_additional_user_info_identity_user_id");

                    b.HasIndex("IsCandidate")
                        .HasDatabaseName("ix_additional_user_info_is_candidate");

                    b.HasIndex("IsExpert")
                        .HasDatabaseName("ix_additional_user_info_is_expert");

                    b.ToTable("additional_user_infos", "public");
                });

            modelBuilder.Entity("InterviewTraining.Domain.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Уникальный идентификатор");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_utc")
                        .HasComment("Дата и время создания записи в таблице");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasComment("Признак удалена запись или нет");

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modified_utc")
                        .HasComment("Дата и время последнего изменения записи в таблице");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("name")
                        .HasComment("Наимнование навыка");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("skills", "public");
                });

            modelBuilder.Entity("InterviewTraining.Domain.SkillGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Уникальный идентификатор");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_utc")
                        .HasComment("Дата и время создания записи в таблице");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasComment("Признак удалена запись или нет");

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modified_utc")
                        .HasComment("Дата и время последнего изменения записи в таблице");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("name")
                        .HasComment("Наимнование группы");

                    b.Property<Guid?>("ParentGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_group_id");

                    b.HasKey("Id");

                    b.HasIndex("ParentGroupId");

                    b.ToTable("skill_groups", "public");
                });

            modelBuilder.Entity("InterviewTraining.Domain.SkillTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Уникальный идентификатор");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_utc")
                        .HasComment("Дата и время создания записи в таблице");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasComment("Признак удалена запись или нет");

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modified_utc")
                        .HasComment("Дата и время последнего изменения записи в таблице");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("name")
                        .HasComment("Наимнование группы");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.ToTable("skill_tags", "public");
                });

            modelBuilder.Entity("InterviewTraining.Domain.UserRating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Уникальный идентификатор");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("comment")
                        .HasComment("Комментарий к рейтингу");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_utc")
                        .HasComment("Дата и время создания записи в таблице");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasComment("Признак удалена запись или нет");

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modified_utc")
                        .HasComment("Дата и время последнего изменения записи в таблице");

                    b.Property<int>("RatingValue")
                        .HasColumnType("integer")
                        .HasColumnName("rating_value")
                        .HasComment("Значение рейтинга от 1 до 5");

                    b.Property<Guid>("UserFromId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_from_id")
                        .HasComment("Идентификатор пользователя, который поставил рейтинг");

                    b.Property<Guid>("UserToId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_to_id")
                        .HasComment("Идентификатор пользователя, которому поставили рейтинг");

                    b.HasKey("Id");

                    b.HasIndex("UserToId")
                        .HasDatabaseName("ix_user_rating_user_to_id");

                    b.HasIndex("UserFromId", "UserToId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_rating_user_from_to");

                    b.ToTable("user_ratings", "public");
                });

            modelBuilder.Entity("InterviewTraining.Domain.Skill", b =>
                {
                    b.HasOne("InterviewTraining.Domain.SkillGroup", "Group")
                        .WithMany("Skills")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.Navigation("Group");
                });

            modelBuilder.Entity("InterviewTraining.Domain.SkillGroup", b =>
                {
                    b.HasOne("InterviewTraining.Domain.SkillGroup", "ParentGroup")
                        .WithMany("ChildGroups")
                        .HasForeignKey("ParentGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentGroup");
                });

            modelBuilder.Entity("InterviewTraining.Domain.SkillTag", b =>
                {
                    b.HasOne("InterviewTraining.Domain.Skill", "Skill")
                        .WithMany("Tags")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("InterviewTraining.Domain.UserRating", b =>
                {
                    b.HasOne("InterviewTraining.Domain.AdditionalUserInfo", "UserFrom")
                        .WithMany("MyRatingToUsers")
                        .HasForeignKey("UserFromId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("InterviewTraining.Domain.AdditionalUserInfo", "UserTo")
                        .WithMany("RatingFromUsers")
                        .HasForeignKey("UserToId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("UserFrom");

                    b.Navigation("UserTo");
                });

            modelBuilder.Entity("InterviewTraining.Domain.AdditionalUserInfo", b =>
                {
                    b.Navigation("MyRatingToUsers");

                    b.Navigation("RatingFromUsers");
                });

            modelBuilder.Entity("InterviewTraining.Domain.Skill", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("InterviewTraining.Domain.SkillGroup", b =>
                {
                    b.Navigation("ChildGroups");

                    b.Navigation("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
