// <auto-generated />
using System;
using InterviewTraining.Infrastructure.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InterviewTraining.Infrastructure.Migrations
{
    [DbContext(typeof(InterviewContext))]
    partial class InterviewContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InterviewTraining.Domain.AdditionalUserInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Уникальный идентификатор");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_utc")
                        .HasComment("Дата и время создания записи в таблице");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description")
                        .HasComment("Полное описание");

                    b.Property<string>("FullName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("full_name")
                        .HasComment("Полное имя пользователя");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("identity_user_id")
                        .HasComment("Идентификатор пользователя в Identity");

                    b.Property<bool>("IsCandidate")
                        .HasColumnType("boolean")
                        .HasColumnName("is_candidate")
                        .HasComment("Признак кандидата");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasComment("Признак удалена запись или нет");

                    b.Property<bool>("IsExpert")
                        .HasColumnType("boolean")
                        .HasColumnName("is_expert")
                        .HasComment("Признак эксперта");

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modified_utc")
                        .HasComment("Дата и время последнего изменения записи в таблице");

                    b.Property<byte[]>("PhotoLocal")
                        .HasColumnType("bytea")
                        .HasColumnName("photo_local")
                        .HasComment("Фото пользователя");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("photo_url")
                        .HasComment("URL фото пользователя");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("short_description")
                        .HasComment("Краткое описание");

                    b.Property<Guid?>("TimeZoneId")
                        .HasColumnType("uuid")
                        .HasColumnName("time_zone_id")
                        .HasComment("Идентификатор часового пояса пользователя");

                    b.HasKey("Id");

                    b.HasIndex("IdentityUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_additional_user_info_identity_user_id");

                    b.HasIndex("IsCandidate")
                        .HasDatabaseName("ix_additional_user_info_is_candidate");

                    b.HasIndex("IsExpert")
                        .HasDatabaseName("ix_additional_user_info_is_expert");

                    b.HasIndex("TimeZoneId");

                    b.ToTable("additional_user_infos", "public");
                });

            modelBuilder.Entity("InterviewTraining.Domain.Interview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Уникальный идентификатор");

                    b.Property<Guid?>("ActiveInterviewVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("active_interview_version_id")
                        .HasComment("Идентификатор активной версии интервью");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_id")
                        .HasComment("Идентификатор кандидата");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_utc")
                        .HasComment("Дата и время создания записи в таблице");

                    b.Property<Guid>("ExpertId")
                        .HasColumnType("uuid")
                        .HasColumnName("expert_id")
                        .HasComment("Идентификатор эксперта");

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modified_utc")
                        .HasComment("Дата и время последнего изменения записи в таблице");

                    b.HasKey("Id");

                    b.HasIndex("ActiveInterviewVersionId")
                        .HasDatabaseName("ix_interviews_active_interview_version_id");

                    b.HasIndex("CandidateId")
                        .HasDatabaseName("ix_interviews_candidate_id");

                    b.HasIndex("ExpertId")
                        .HasDatabaseName("ix_interviews_expert_id");

                    b.ToTable("interviews", "public");
                });

            modelBuilder.Entity("InterviewTraining.Domain.InterviewLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Уникальный идентификатор");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code")
                        .HasComment("Код");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_utc")
                        .HasComment("Дата и время создания записи в таблице");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modified_utc")
                        .HasComment("Дата и время последнего изменения записи в таблице");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name_en")
                        .HasComment("Наименование языка по английски");

                    b.Property<string>("NameRu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name_ru")
                        .HasComment("Наименование языка по русски");

                    b.HasKey("Id");

                    b.ToTable("interview_languages", "public");
                });

            modelBuilder.Entity("InterviewTraining.Domain.InterviewVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Уникальный идентификатор");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_utc")
                        .HasComment("Дата и время создания записи в таблице");

                    b.Property<DateTime?>("EndUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_utc")
                        .HasComment("Конец собеседования в UTC");

                    b.Property<Guid>("InterviewId")
                        .HasColumnType("uuid")
                        .HasColumnName("interview_id")
                        .HasComment("Идентификатор интервью");

                    b.Property<Guid?>("LanguageId")
                        .HasColumnType("uuid")
                        .HasColumnName("language_id")
                        .HasComment("Идентификатор языка");

                    b.Property<string>("LinkToVideoCall")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("link_to_video_call")
                        .HasComment("Ссылка на видеозвонок");

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modified_utc")
                        .HasComment("Дата и время последнего изменения записи в таблице");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_utc")
                        .HasComment("Начало собеседования в UTC");

                    b.HasKey("Id");

                    b.HasIndex("InterviewId")
                        .HasDatabaseName("ix_interview_versions_interview_id");

                    b.HasIndex("LanguageId");

                    b.ToTable("interview_versions", "public");
                });

            modelBuilder.Entity("InterviewTraining.Domain.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Уникальный идентификатор");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_utc")
                        .HasComment("Дата и время создания записи в таблице");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasComment("Признак удалена запись или нет");

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modified_utc")
                        .HasComment("Дата и время последнего изменения записи в таблице");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("name")
                        .HasComment("Наимнование навыка");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("skills", "public");
                });

            modelBuilder.Entity("InterviewTraining.Domain.SkillGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Уникальный идентификатор");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_utc")
                        .HasComment("Дата и время создания записи в таблице");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasComment("Признак удалена запись или нет");

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modified_utc")
                        .HasComment("Дата и время последнего изменения записи в таблице");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("name")
                        .HasComment("Наимнование группы");

                    b.Property<Guid?>("ParentGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_group_id");

                    b.HasKey("Id");

                    b.HasIndex("ParentGroupId");

                    b.ToTable("skill_groups", "public");
                });

            modelBuilder.Entity("InterviewTraining.Domain.SkillTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Уникальный идентификатор");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_utc")
                        .HasComment("Дата и время создания записи в таблице");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasComment("Признак удалена запись или нет");

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modified_utc")
                        .HasComment("Дата и время последнего изменения записи в таблице");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("name")
                        .HasComment("Наимнование группы");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.ToTable("skill_tags", "public");
                });

            modelBuilder.Entity("InterviewTraining.Domain.TimeZone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Уникальный идентификатор");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code")
                        .HasComment("Код часового пояса");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_utc")
                        .HasComment("Дата и время создания записи в таблице");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description")
                        .HasComment("Наименование часового пояса");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasComment("Признак удалена запись или нет");

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modified_utc")
                        .HasComment("Дата и время последнего изменения записи в таблице");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_time_zones_code");

                    b.ToTable("time_zones", "public");
                });

            modelBuilder.Entity("InterviewTraining.Domain.UserAvailableTime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Уникальный идентификатор");

                    b.Property<int>("AvailabilityType")
                        .HasColumnType("integer")
                        .HasColumnName("availability_type")
                        .HasComment("Тип доступности: 0=AlwaysAvailable, 1=WeeklyFullDay, 2=WeeklyWithTime, 3=SpecificDateTime");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_utc")
                        .HasComment("Дата и время создания записи в таблице");

                    b.Property<int?>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week")
                        .HasComment("День недели (0-6), если применимо");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_time")
                        .HasComment("Время окончания в UTC");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasComment("Признак удалена запись или нет");

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modified_utc")
                        .HasComment("Дата и время последнего изменения записи в таблице");

                    b.Property<DateOnly?>("SpecificDate")
                        .HasColumnType("date")
                        .HasColumnName("specific_date")
                        .HasComment("Конкретная дата, если применимо");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time")
                        .HasComment("Время начала в UTC");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasComment("Идентификатор пользователя (эксперта)");

                    b.HasKey("Id");

                    b.HasIndex("AvailabilityType")
                        .HasDatabaseName("ix_user_available_times_availability_type");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_available_times_user_id");

                    b.ToTable("user_available_times", "public");
                });

            modelBuilder.Entity("InterviewTraining.Domain.UserRating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Уникальный идентификатор");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("comment")
                        .HasComment("Комментарий к рейтингу");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_utc")
                        .HasComment("Дата и время создания записи в таблице");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasComment("Признак удалена запись или нет");

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modified_utc")
                        .HasComment("Дата и время последнего изменения записи в таблице");

                    b.Property<int>("RatingValue")
                        .HasColumnType("integer")
                        .HasColumnName("rating_value")
                        .HasComment("Значение рейтинга от 1 до 5");

                    b.Property<Guid>("UserFromId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_from_id")
                        .HasComment("Идентификатор пользователя, который поставил рейтинг");

                    b.Property<Guid>("UserToId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_to_id")
                        .HasComment("Идентификатор пользователя, которому поставили рейтинг");

                    b.HasKey("Id");

                    b.HasIndex("UserToId")
                        .HasDatabaseName("ix_user_rating_user_to_id");

                    b.HasIndex("UserFromId", "UserToId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_rating_user_from_to");

                    b.ToTable("user_ratings", "public");
                });

            modelBuilder.Entity("InterviewTraining.Domain.UserSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Уникальный идентификатор");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_utc")
                        .HasComment("Дата и время создания записи в таблице");

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modified_utc")
                        .HasComment("Дата и время последнего изменения записи в таблице");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid")
                        .HasColumnName("skill_id")
                        .HasComment("Идентификатор навыка");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasComment("Идентификатор пользователя");

                    b.HasKey("Id");

                    b.HasIndex("SkillId")
                        .HasDatabaseName("ix_user_skills_skill_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_skills_user_id");

                    b.HasIndex("UserId", "SkillId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_skills_user_id_skill_id");

                    b.ToTable("user_skills", "public");
                });

            modelBuilder.Entity("InterviewTraining.Domain.AdditionalUserInfo", b =>
                {
                    b.HasOne("InterviewTraining.Domain.TimeZone", "TimeZone")
                        .WithMany()
                        .HasForeignKey("TimeZoneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TimeZone");
                });

            modelBuilder.Entity("InterviewTraining.Domain.Interview", b =>
                {
                    b.HasOne("InterviewTraining.Domain.InterviewVersion", "ActiveInterviewVersion")
                        .WithMany()
                        .HasForeignKey("ActiveInterviewVersionId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("InterviewTraining.Domain.AdditionalUserInfo", "Candidate")
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("InterviewTraining.Domain.AdditionalUserInfo", "Expert")
                        .WithMany()
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("ActiveInterviewVersion");

                    b.Navigation("Candidate");

                    b.Navigation("Expert");
                });

            modelBuilder.Entity("InterviewTraining.Domain.InterviewVersion", b =>
                {
                    b.HasOne("InterviewTraining.Domain.Interview", "Interview")
                        .WithMany("Versions")
                        .HasForeignKey("InterviewId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("InterviewTraining.Domain.InterviewLanguage", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.OwnsOne("InterviewTraining.Domain.BaseUserInterviewData", "Expert", b1 =>
                        {
                            b1.Property<Guid>("InterviewVersionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CancellReason")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("expert_cancell_reason")
                                .HasComment("Причина отмены экспертом");

                            b1.Property<bool>("IsApproved")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("expert_is_approved")
                                .HasComment("Признак подтверждения экспертом");

                            b1.Property<bool>("IsCancelled")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("expert_is_cancelled")
                                .HasComment("Признак отмены экспертом");

                            b1.Property<bool>("IsPaid")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("expert_is_paid")
                                .HasComment("Признак оплаты экспертом");

                            b1.HasKey("InterviewVersionId");

                            b1.ToTable("interview_versions", "public");

                            b1.WithOwner()
                                .HasForeignKey("InterviewVersionId");
                        });

                    b.OwnsOne("InterviewTraining.Domain.CandidateInterviewData", "Candidate", b1 =>
                        {
                            b1.Property<Guid>("InterviewVersionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CancellReason")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("candidate_cancell_reason")
                                .HasComment("Причина отмены кандидатом");

                            b1.Property<bool>("IsApproved")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("candidate_is_approved")
                                .HasComment("Признак подтверждения кандидатом");

                            b1.Property<bool>("IsCancelled")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("candidate_is_cancelled")
                                .HasComment("Признак отмены кандидатом");

                            b1.Property<bool>("IsPaid")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("candidate_is_paid")
                                .HasComment("Признак оплаты кандидатом");

                            b1.Property<string>("Notes")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("notes")
                                .HasComment("Примечания от кандидата при бронировании");

                            b1.HasKey("InterviewVersionId");

                            b1.ToTable("interview_versions", "public");

                            b1.WithOwner()
                                .HasForeignKey("InterviewVersionId");
                        });

                    b.Navigation("Candidate");

                    b.Navigation("Expert");

                    b.Navigation("Interview");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("InterviewTraining.Domain.Skill", b =>
                {
                    b.HasOne("InterviewTraining.Domain.SkillGroup", "Group")
                        .WithMany("Skills")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.Navigation("Group");
                });

            modelBuilder.Entity("InterviewTraining.Domain.SkillGroup", b =>
                {
                    b.HasOne("InterviewTraining.Domain.SkillGroup", "ParentGroup")
                        .WithMany("ChildGroups")
                        .HasForeignKey("ParentGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentGroup");
                });

            modelBuilder.Entity("InterviewTraining.Domain.SkillTag", b =>
                {
                    b.HasOne("InterviewTraining.Domain.Skill", "Skill")
                        .WithMany("Tags")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("InterviewTraining.Domain.UserAvailableTime", b =>
                {
                    b.HasOne("InterviewTraining.Domain.AdditionalUserInfo", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InterviewTraining.Domain.UserRating", b =>
                {
                    b.HasOne("InterviewTraining.Domain.AdditionalUserInfo", "UserFrom")
                        .WithMany("MyRatingToUsers")
                        .HasForeignKey("UserFromId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("InterviewTraining.Domain.AdditionalUserInfo", "UserTo")
                        .WithMany("RatingFromUsers")
                        .HasForeignKey("UserToId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("UserFrom");

                    b.Navigation("UserTo");
                });

            modelBuilder.Entity("InterviewTraining.Domain.UserSkill", b =>
                {
                    b.HasOne("InterviewTraining.Domain.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InterviewTraining.Domain.AdditionalUserInfo", "User")
                        .WithMany("Skills")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InterviewTraining.Domain.AdditionalUserInfo", b =>
                {
                    b.Navigation("MyRatingToUsers");

                    b.Navigation("RatingFromUsers");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("InterviewTraining.Domain.Interview", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("InterviewTraining.Domain.Skill", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("InterviewTraining.Domain.SkillGroup", b =>
                {
                    b.Navigation("ChildGroups");

                    b.Navigation("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
