// <auto-generated />
using System;
using InterviewTraining.Infrastructure.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InterviewTraining.Infrastructure.Migrations
{
    [DbContext(typeof(InterviewContext))]
    partial class InterviewContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InterviewTraining.Domain.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Уникальный идентификатор");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_utc")
                        .HasComment("Дата и время создания записи в таблице");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasComment("Признак удалена запись или нет");

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modified_utc")
                        .HasComment("Дата и время последнего изменения записи в таблице");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("name")
                        .HasComment("Наимнование навыка");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("skill", "public");
                });

            modelBuilder.Entity("InterviewTraining.Domain.SkillGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Уникальный идентификатор");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_utc")
                        .HasComment("Дата и время создания записи в таблице");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasComment("Признак удалена запись или нет");

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modified_utc")
                        .HasComment("Дата и время последнего изменения записи в таблице");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("name")
                        .HasComment("Наимнование группы");

                    b.Property<Guid?>("ParentGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_group_id");

                    b.HasKey("Id");

                    b.HasIndex("ParentGroupId");

                    b.ToTable("skill_groups", "public");
                });

            modelBuilder.Entity("InterviewTraining.Domain.SkillTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Уникальный идентификатор");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_utc")
                        .HasComment("Дата и время создания записи в таблице");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasComment("Признак удалена запись или нет");

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modified_utc")
                        .HasComment("Дата и время последнего изменения записи в таблице");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("name")
                        .HasComment("Наимнование группы");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.ToTable("skill_tags", "public");
                });

            modelBuilder.Entity("InterviewTraining.Domain.Skill", b =>
                {
                    b.HasOne("InterviewTraining.Domain.SkillGroup", "Group")
                        .WithMany("Skills")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.Navigation("Group");
                });

            modelBuilder.Entity("InterviewTraining.Domain.SkillGroup", b =>
                {
                    b.HasOne("InterviewTraining.Domain.SkillGroup", "ParentGroup")
                        .WithMany("ChildGroups")
                        .HasForeignKey("ParentGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentGroup");
                });

            modelBuilder.Entity("InterviewTraining.Domain.SkillTag", b =>
                {
                    b.HasOne("InterviewTraining.Domain.Skill", "Skill")
                        .WithMany("Tags")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("InterviewTraining.Domain.Skill", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("InterviewTraining.Domain.SkillGroup", b =>
                {
                    b.Navigation("ChildGroups");

                    b.Navigation("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
